spring:
  datasource:
    url: jdbc:mysql://mysql:3306/im?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
  rabbitmq:
    host: rabbitmq
  redis:
    host: redis
  attachment:
    path: /apps/launchrAttachment/
